import { Activity, BrainCircuit, CheckCircle2, Flame, Gauge, KeyRound, Medal, Target, Trophy, Zap } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";

const Stat = ({ label, value, icon: Icon, accent = "text-cyan-300" }) => <div className="glass p-5"><div className={`flex items-center gap-2 font-mono text-[10px] tracking-[.16em] text-slate-600`}><Icon className={accent} size={15}/>{label}</div><div className="mt-4 font-mono text-3xl font-bold text-white">{value}</div></div>;
export default function Dashboard({ stats }) {
  const navigate = useNavigate();
  const user = stats.user || {};
  const ai = stats.aiProfile || {};
  const weakKeys = ai.weakKeyBank?.length ? ai.weakKeyBank : stats.weakKeys || [];
  const weakWords = ai.weakWordBank?.length ? ai.weakWordBank : stats.weakWords || [];
  const startWeakPractice = (kind = "mixed") => {
    sessionStorage.setItem("typotoxic_practice_seed", JSON.stringify({
      kind,
      weakKeys,
      weakWords,
      focus: kind === "keys" ? "weak key practice" : kind === "words" ? "weak word practice" : "mixed weakness practice",
      createdAt: Date.now(),
    }));
    navigate("/training");
  };
  return <div className="space-y-5">
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Stat label="LATEST WPM" value={stats.latestWpm || 0} icon={Zap}/><Stat label="BEST WPM" value={stats.bestWpm || 0} icon={Trophy} accent="text-purple-400"/><Stat label="AI DIFFICULTY" value={ai.difficulty || 3} icon={BrainCircuit} accent="text-cyan-300"/><Stat label="AVG ACCURACY" value={`${stats.averageAccuracy || 0}%`} icon={Target} accent="text-green-400"/></div>
    <div className="grid gap-5 lg:grid-cols-[1fr_320px]">
      <div className="glass p-5"><div className="flex items-center gap-2 font-mono text-xs font-bold tracking-widest text-cyan-300"><Activity size={15}/> PERFORMANCE_CURVE</div><div className="mt-6 h-64"><ResponsiveContainer width="100%" height="100%"><AreaChart data={stats.history || []}><defs><linearGradient id="wpm" x1="0" x2="0" y1="0" y2="1"><stop offset="5%" stopColor="#26f0ff" stopOpacity={.4}/><stop offset="95%" stopColor="#26f0ff" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="#172235" strokeDasharray="3 3"/><XAxis dataKey="test" stroke="#536176" fontSize={10}/><YAxis stroke="#536176" fontSize={10}/><Tooltip contentStyle={{ background: "#08101c", border: "1px solid #234" }}/><Area type="monotone" dataKey="wpm" stroke="#26f0ff" fill="url(#wpm)"/></AreaChart></ResponsiveContainer></div></div>
      <div className="glass p-5"><div className="font-mono text-xs font-bold tracking-widest text-purple-300">OPERATOR_PROFILE</div><div className="mt-6 flex items-center gap-4"><div className="grid h-14 w-14 place-items-center border border-purple-400/40 bg-purple-500/10 font-mono text-xl font-bold text-purple-300">{user.name?.[0] || "?"}</div><div><div className="font-bold text-white">{user.name}</div><div className="mt-1 text-xs text-slate-500">{user.level}</div></div></div><div className="mt-6 space-y-3">{[[Medal,"XP",user.xp || 0],[Flame,"Streak",`${user.streak || 0} day`],[KeyRound,"Weak keys",stats.weakKeys?.map((item) => item.key).join(" ") || "none"]].map(([Icon,label,value]) => <div key={label} className="flex items-center justify-between border-t border-white/5 pt-3 text-xs"><span className="flex items-center gap-2 text-slate-500"><Icon size={14}/>{label}</span><span className="font-mono text-slate-200">{value}</span></div>)}</div></div>
    </div>
    <div className="grid gap-5 lg:grid-cols-3">
      <div className="glass p-5"><div className="font-mono text-xs font-bold tracking-widest text-cyan-300">AI_PREDICTIONS</div><div className="mt-4 grid grid-cols-2 gap-2"><div className="border border-cyan-400/10 bg-cyan-400/[.03] p-3"><span className="text-[10px] text-slate-600">7 day WPM</span><b className="block font-mono text-xl text-cyan-300">{ai.projectedWpm7Days || "--"}</b></div><div className="border border-cyan-400/10 bg-cyan-400/[.03] p-3"><span className="text-[10px] text-slate-600">7 day ACC</span><b className="block font-mono text-xl text-cyan-300">{ai.projectedAccuracy7Days ? `${ai.projectedAccuracy7Days}%` : "--"}</b></div></div><div className="mt-4 space-y-2">{ai.predictedWeakAreas?.length ? ai.predictedWeakAreas.map((item) => <div key={item} className="border border-cyan-400/10 bg-cyan-400/[.03] px-3 py-2 text-xs text-slate-300">{item}</div>) : <p className="text-sm text-slate-600">Run more sessions to train the prediction model.</p>}</div></div>
      <div className="glass p-5"><div className="font-mono text-xs font-bold tracking-widest text-purple-300">ADAPTIVE_MISSIONS</div><div className="mt-4 space-y-3">{ai.adaptiveMissions?.length ? ai.adaptiveMissions.map((mission) => <div key={mission.title}><div className="flex items-center justify-between text-xs"><span className="text-slate-300">{mission.title}</span><span className="text-slate-600">{Math.round(mission.progress || 0)}%</span></div><div className="mt-2 h-1.5 bg-white/5"><div className="h-full bg-purple-400" style={{ width: `${Math.min(100, mission.progress || 0)}%` }}/></div><p className="mt-1 text-[10px] text-slate-600">{mission.target}</p></div>) : <p className="text-sm text-slate-600">Missions appear after your first saved run.</p>}</div></div>
      <div className="glass p-5"><div className="font-mono text-xs font-bold tracking-widest text-green-400">ACHIEVEMENTS</div><div className="mt-4 space-y-2">{ai.achievements?.length ? ai.achievements.slice(-5).map((item) => <div key={item.key} className="flex items-center gap-2 border border-green-400/10 bg-green-400/[.03] px-3 py-2 text-xs text-slate-300"><CheckCircle2 size={13} className="text-green-400"/>{item.title}</div>) : <p className="text-sm text-slate-600">No achievements unlocked yet.</p>}</div></div>
    </div>
    <div className="glass p-5"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><div className="font-mono text-xs font-bold tracking-widest text-green-400">WEAKNESS_BANK</div><p className="mt-1 text-xs text-slate-600">Every mistake updates this collection. Generate unlimited practice tests from it.</p></div><div className="flex flex-wrap gap-2"><button onClick={() => startWeakPractice("keys")} className="bg-cyan-300 px-3 py-2 font-mono text-[10px] font-bold uppercase tracking-widest text-slate-950">weak keys test</button><button onClick={() => startWeakPractice("words")} className="border border-purple-400/40 px-3 py-2 font-mono text-[10px] font-bold uppercase tracking-widest text-purple-300">weak words test</button><button onClick={() => startWeakPractice("mixed")} className="border border-green-400/40 px-3 py-2 font-mono text-[10px] font-bold uppercase tracking-widest text-green-300">ai mixed test</button></div></div><div className="mt-5 grid gap-4 md:grid-cols-2"><div><div className="mb-2 text-[10px] uppercase tracking-widest text-slate-600">wrong buttons</div><div className="flex flex-wrap gap-2">{weakKeys.length ? weakKeys.map((item) => <span key={item.key} className="border border-cyan-400/20 bg-cyan-400/5 px-3 py-2 font-mono text-xs text-cyan-300">{item.key} <small className="text-slate-600">x{item.count}</small></span>) : <span className="text-sm text-slate-600">No weak keys yet.</span>}</div></div><div><div className="mb-2 text-[10px] uppercase tracking-widest text-slate-600">weak words</div><div className="flex flex-wrap gap-2">{weakWords.length ? weakWords.map((item) => <span key={item.word} className="border border-red-400/20 bg-red-400/5 px-3 py-2 font-mono text-xs text-red-300">{item.word} <small className="text-slate-600">x{item.count}</small></span>) : <span className="text-sm text-slate-600">No weak words yet.</span>}</div></div></div></div>
  </div>;
}
